version: "3.4"

services:
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017-27019:27017-27019' 
    networks: 
      - shortener

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: base
    links:
      - mongo
    environment:
      - ENV_NAME=dev
      - DB_SERVER=mongo
      - URL_PREFIX=https://pbid.io
      - MONGO_URL=mongo
      - MONGO_PORT=27017
      - DB_NAME=shortUrl
    command: npm start
    ports:
      - 8080:8080
    depends_on:
      - mongo
    networks: 
      - shortener

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - 8082:80
    networks: 
      - shortener
    depends_on:
      - api
  
networks:
  shortener:
    driver: "bridge"