version: "3.4"

services:

  ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - 8082:80
    networks: 
      - ui

  ui-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    command: npm run test:unit
    networks:
      - ui
  
networks:
  ui:
    driver: "bridge"