version: "3.4"

services:
  mongo:
    image: 'mongo:latest'
    ports:
      - '27017-27019:27017-27019' 
    networks: 
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    links:
      - mongo
    environment:
      - ENV_NAME=dev
      - DB_SERVER=mongo
      - URL_PREFIX=https://pbid.io
      - MONGO_URL=mongo
      - MONGO_PORT=27017
      - DB_NAME=shortUrl
    command: npm start
    ports:
      - 8080:8080
    depends_on:
      - mongo
    networks: 
      - backend

  api-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    links:
      - mongo
    environment:
      - ENV_NAME=dev
      - DB_SERVER=mongo
    command: npm run test
    depends_on:
      - mongo
    networks: 
      - backend
  
networks:
  backend:
    driver: "bridge"